/*--------------------------------------------------------------------------
M¢dulo    : Manejo de la Pantalla.
Archivo   : BUTTON.H.
Objetivo  : Contiene las definiciones de funciones para el uso de botones
				gr ficos.
Dise¤o    : Jos‚ Antonio Valderrama Ramos.
Implemento: El mismo.
Versi¢n   : 1.00 (Marzo '94).
--------------------------------------------------------------------------*/

#ifndef BUTTON
	#define BUTTON
	void _draw_button(int,int,int,int,int,int,int,int,int);
#endif
