/* =========================================================================
							  INSTITUTO TECNOLOGICO DE MORELIA
										  Bases de Datos

M¢dulo     : Cabecera funciones principales del manejador.
Archivo    : BD01.H
Objetivo   : Archivo que contiene funciones de nivel bajo para el
				 manejador.
Dise¤o     : Jos‚ Antonio Valderrama Ramos  -  90120509-9
				 Jorge Edurado Aparicio Mayorga  -  90120511-3
Implemento : Los mismos.
Versi¢n    : 1.00 (Febrero-Marzo 1994).
========================================================================= */

#define FONDO_VENT	0x79
#define MARCO_VENT	0x78
#define C_TITULO		0x39
#define C_ESPERA		0xF
#define C_TONY       0x75
#define C_TONY_2     0x7C
