/* +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
						 INGENIERIA EN SISTEMAS COMPUTACIONALES
										Sistemas Operativos
M¢dulo     : Definiciones.
Archivo    : graf-ms3.h
Objetivo   : Definiciones para el uso de gr ficos.
Dise¤o     : Jorge Eduardo Aparicio Mayorga  -  90120511-3,
				 Jos‚ Antonio Valderrama Ramos  -  90120509-9.
Implemento : Los mismos.
Versi¢n    : Noviembre 1993.
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+ */

#define OPEN 1               /* Constantes para abrir y cerrar la puerta. */
#define CLOSE 0

#define LISTO_2_EXEC 0       /* Constantes para la animaci¢n de procesos. */
#define EXEC_2_LISTO 1
#define LISTO_2_SLISTO 2
#define SLISTO_2_LISTO 3
#define EXEC_2_SLISTO 4
#define LISTO_2_BLOQ 5
#define BLOQ_2_LISTO 6
#define SLISTO_2_SBLOQ 7
#define SBLOQ_2_SLISTO 8
#define EXEC_2_BLOQ 9
#define SBLOQ_2_BLOQ 10
#define BLOQ_2_SBLOQ 11
